# Generated by Django 2.0.2 on 2018-09-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=40)),
                ('salt', models.CharField(max_length=20, null=True)),
                ('status', models.BooleanField()),
                ('note', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 't_user',
            },
        ),
    ]
